services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_LOGIN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DOCKER_NAME}
    ports:
    - "5434:5432"
    volumes:
    - postgres:/var/lib/postgresql/data

  fastapi:
    image: hh_parser
    build: ./
    container_name: hh_parser
    restart: always
    volumes:
      - .:/code/
    expose:
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
#      - redis
    env_file:
      - ./.env

#  redis:
#    image: redis:7

volumes:
  postgres:
  static:
