services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_LOGIN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DOCKER_NAME}
    ports:
    - "5434:5432"
    volumes:
    - postgres:/var/lib/postgresql/data

  fastapi:
    image: hh_parser
    build: ./
    container_name: hh_parser
    restart: always
    volumes:
      - .:/code/
    expose:
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env

  celery:
    build: ./
    command: bash -c "celery -A celery_app.celery_app.celery_app worker --loglevel=INFO"
    volumes:
      - .:/code/
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - fastapi
      - redis

  redis:
    image: redis:7

  dashboard:
    build: ./
    command: celery --broker=${CELERY_BROKER_URL} flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - fastapi
      - redis
      - celery


volumes:
  postgres:
  static:
